### ISSUE TITLE
Pip install jgtextrank doesn't work

### ISSUE THREAD

**Issue by PandaWhoCodes** [jerrygaoLondon/jgtextrank#2]
```
Collecting jgtextrank
  Downloading https://files.pythonhosted.org/packages/b3/bd/91d6b9590e8e471138d40b23c60da7db8acf576422977d43646566c0b4a9/jgtextrank-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-hsk486_a\jgtextrank\setup.py", line 29, in <module>
        long_description=readme(),
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-hsk486_a\jgtextrank\setup.py", line 7, in readme
        with open('readme.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ashis\AppData\Local\Temp\pip-install-hsk486_a\jgtextrank\
```

**Comment by jerrygaoLondon** [comment]
Resolved and thanks for spotting the issue.
