### ISSUE TITLE
An attempt has been made tostart a new process before the current process has finished its bootstrapping phase

### ISSUE THREAD

**Issue by PandaWhoCodes** [jerrygaoLondon/jgtextrank#3]
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\python3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\python3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\python3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\python3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\python3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ashis\Documents\infoassistants\TA backend\tests_.py", line 7, in <module>
    keywords = keywords_extraction("\n".join(text), top_p=1, directed=False)[0][:15]
  File "C:\python3\lib\site-packages\jgtextrank-0.1.3-py3.7.egg\jgtextrank\core.py", line 1103, in keywords_extraction
    weight_comb=weight_comb, mu=mu)
  File "C:\python3\lib\site-packages\jgtextrank-0.1.3-py3.7.egg\jgtextrank\core.py", line 796, in _keywords_extraction_from_preprocessed_context
    window=window)
  File "C:\python3\lib\site-packages\jgtextrank-0.1.3-py3.7.egg\jgtextrank\core.py", line 510, in build_cooccurrence_graph
    conn_with_original_ctx=conn_with_original_ctx, window_size=window)
  File "C:\python3\lib\site-packages\jgtextrank-0.1.3-py3.7.egg\jgtextrank\core.py", line 432, in _build_vertices_representations
    with Pool(processes=MAX_PROCESSES) as pool:
  File "C:\python3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\python3\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\python3\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\python3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\python3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\python3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\python3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\python3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 

```
Python version 3.7.2

**Comment by PandaWhoCodes** [comment]
It's an issue with windows multiprocessing.
Adding a `if __name__ == '__main__':` while calling the function fixes the issue
